export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_PLAYERS_LOADING = "SET_PLAYERS_LOADING";
export const GET_PLAYERS = "GET_PLAYERS";
export const GET_PLAYER = "GET_PLAYER";

export const GET_MATCHES = "GET_MATCHES";
export const SET_MATCHES_LOADING = "SET_MATCHES_LOADING";
export const MATCH_DETAILS = "MATCH_DETAILS";

export const FETCH_PLAYERS_SAGA = "FETCH_PLAYERS_SAGA";
export const FETCH_PLAYER_SAGA = "FETCH_PLAYER_SAGA";

export const ADD_PLAYER_SAGA = "ADD_PLAYER_SAGA";

export const GET_RANKINGS_SAGA = "GET_RANKINGS_SAGA";

export const FETCH_MATCHES_SAGA = "FETCH_MATCHES_SAGA";
export const FETCH_MATCH_SAGA = "FETCH_MATCH_SAGA";
export const ADD_MATCH_SAGA = "ADD_MATCH_SAGA";
